config/routes.rb
Rails.application.routes.draw do

  get 'global_configurations/putsNotes'
  patch 'global_configurations/update'

  root 'main#index'

  devise_for :users

  resources :courses do
    collection do
      post 'addMoreRows'
    end
  end
  resources :periods do
    member do
      get 'desactivate'
      get 'get_grades'
    end
  end
  resources :homeworks do
    collection do
      post 'complete'
    end
    member do
      get 'desactivate'
      get 'particulary_homework'
    end
  end
  resources :notices do
    collection do
      get 'show_all'
      post 'addRow'
    end
  end
  resources :assists do
    member do
      post 'history'
      get 'particulary_assist'
    end
  end
  resources :teachers
  resources :auxiliaries
  resources :degrees
  resources :timetables do
    collection do
      post 'addMoreRows'
      post 'complete'
    end
  end
  resources :enrolments
  resources :sections_degrees do
    collection do
      post 'addAuxiliaries'
    end
  end
  resources :users, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  resources :grades do
    collection do
      post 'complete'
    end
    member do
      get 'put_grade'
      get 'show_list_students'
      get 'show_grades_student'
      get 'show_report'
      get 'student_grades_pdf'
      post 'student_grades_pdf'
    end
  end

end

app/models/assist.rb
class Assist < ActiveRecord::Base
	has_many :assist_details
	belongs_to :sections_degree
	accepts_nested_attributes_for :assist_details
end

app/models/assist_detail.rb
class AssistDetail < ActiveRecord::Base
	belongs_to :assist
	belongs_to :student
end

app/models/auxiliary.rb
class Auxiliary < User
  has_many :notice_details
  belongs_to :sections_degree_detail
  belongs_to :notice

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_and_belongs_to_many :degrees
	has_many :timetable_details
	has_many :course_details
	has_many :homeworks
	belongs_to :sections_degree

	accepts_nested_attributes_for :course_details, :allow_destroy => true

	has_attached_file :silabus, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	do_not_validate_attachment_file_type :silabus
	#validates_attachment_content_type :silabus, :content_type => /\Aimage\/.*\Z/
end

app/models/course_detail.rb
class CourseDetail < ActiveRecord::Base
  belongs_to :courses
end

app/models/course_grade.rb
class CourseGrade < ActiveRecord::Base
end

app/models/degree.rb
class Degree < ActiveRecord::Base
	has_and_belongs_to_many :courses
	has_many :sections_degrees
end

app/models/grade.rb
class Grade < ActiveRecord::Base
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  belongs_to :courses
  has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
end

app/models/notice.rb
class Notice < ActiveRecord::Base
	has_many :notice_details
	has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
	
	accepts_nested_attributes_for :notice_details, :allow_destroy => true
end

app/models/notice_detail.rb
class NoticeDetail < ActiveRecord::Base
	belongs_to :notice
	belongs_to :teachers
	belongs_to :auxiliaries
	belongs_to :students
end

app/models/period.rb
class Period < ActiveRecord::Base
end

app/models/rating.rb
class Rating < ActiveRecord::Base
end

app/models/student.rb
class Student < User
  has_many :student_details
  has_many :assist_details
  has_many :notice_details
  belongs_to :sections_degree
  belongs_to :notice

  accepts_nested_attributes_for :student_details
end

app/models/student_place.rb
class StudentPlace < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < User
  has_many :timetable_details
  has_many :notice_details
  belongs_to :notice

end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
	has_many :timetable_details
	belongs_to :sections_degree

	accepts_nested_attributes_for :timetable_details, :allow_destroy => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  include RoleModel
  roles :director, :administrator, :assistant, :student, :teacher

end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_filter :authenticate_user!
  def index
    @notices = Notice.all
  end

  def new
    @notice = Notice.new
  end

  def show
    @notice = Notice.find(params[:id])
  end

  def show_all
    if !current_user.type.nil?
      @individual_notices = Array.new
      current_user.notice_details.take(10).each do |d|
        @individual_notices << d.notice
      end
    end
    @notices_important = Notice.where(:important => 1)
    @notices_global = Notice.where(:global_notice => 1)
  end

  def addRow
    @reg_n = ((Time.now.to_f)*100).to_i
    if params[:teacher_selected].to_i != 0
      @teachers = Teacher.all
    end
    if params[:student_selected].to_i != 0
      @students = Student.all
    end
    if params[:auxiliary_selected].to_i != 0
      @auxiliaries = Auxiliary.all
    end
    render(:partial => 'form_row', :layout => false)
  end

  def create
    notice = Notice.new(params_notice)
    notice.save
    notice.notice_details.each do |nd|
      if nd.student_id != nil
        UserMailer.send_notice_to_user(nd.student_id,nd.notice_id).deliver
      end
    end
    redirect_to :action => :index
  end

  def edit
    @action = 'edit'
    @reg_n = ((Time.now.to_f)*100).to_i
    @notice = Notice.find(params[:id])
  end

  def update
    notice = Notice.find(params[:id]).update_attributes(params_notice)
    redirect_to :action => :index
  end

  def destroy
    notice = Notice.destroy(params[:id])
    redirect_to :action => :index
  end

  private
  def params_notice
    params.require(:notice).permit(
      :title, 
      :description,
      :attachment,
      :global_notice,
      :important,
      :date_of_issue,
      notice_details_attributes: [
        :id,
        :notice_id,
        :student_id,
        :auxiliary_id,
        :teacher_id,
        :_destroy
      ]
    )
  end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/notices/_form.html.haml
.row
  .col-md-9.center-block
    / Form Wizard
    .admin-form.theme-primary
      .panel
        = simple_form_for(@notice, html: {id: 'admin-form', autocomplete: 'off' }) do |f|
          .panel-body
            .section-divider.mb40.mt20
              %span Datos de la Noticia

            #alert-1.alert.alert-info.light.alert-dismissable
              %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
              %i.fa.fa-info.pr10
              %strong Aviso!
              Si marcas la noticia como
              %a.alert-link{:href => "#"} Importante
              , esta aparecerá como modal cuando los usuarios o usuario entre al sistema.
            #alert-2.alert.alert-info.light.alert-dismissable
              %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
              %i.fa.fa-info.pr10
              %strong Aviso!
              Los archivos solo pueden ser formato de imagen como
              %a.alert-link{:href => "#"} PNG, JPG, JPEG, GIF
            .section.row
              .col-md-6
                %label.field.prepend-icon{:for => "date_of_issue"}
                  = f.input :date_of_issue, as: :string, placeholder: "Fecha Limite", input_html: { id: 'date_of_issue', class: 'gui-input', :type => "date" }, label: false, :wrapper => false
                  %label.field-icon{:for => "date_of_issue"}
                    %i.fa.fa-user
              .col-md-6
                %label.field.prepend-icon{:for => "title"}
                  = f.input :title, placeholder: "Titulo", input_html: { id: 'title', class: 'gui-input' }, label: false, :wrapper => false
                  %label.field-icon{:for => "title"}
                    %i.fa.fa-user
            .section.row
              .col-md-12
                %label.field.prepend-icon{:for => "description"}
                  = f.input :description, placeholder: "Cuerpo de la Noticia", input_html: { id: 'description', class: 'gui-textarea' }, label: false, :wrapper => false
                  %label.field-icon{:for => "description"}
                    %i.fa.fa-comments
            .section.row
              .col-md-7
                %label.field.prepend-icon.append-button.file{:for => "silabus"}
                  %span.button.btn-primary Seleccionar Archivo
                  = f.input :attachment, as: :file, label: false, :wrapper => false, input_html: { id: 'file', class: 'gui-file', :onchange => "document.getElementById('uploader').value = this.value;"}
                  %input#uploader.gui-input{:placeholder => "Por favor, seleccione un archivo", :type => "text"}/
                  %label.field-icon{:for => "silabus"}
                    %i.fa.fa-upload
                - if @notice.attachment.exists?
                  .alert.alert-sm.alert-border-left.alert-primary.light.alert-dismissable
                    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"}
                    %i.fa.fa-cubes.pr10.hidden
                    %strong Aviso!
                    Este curso ya tiene un
                    %a.alert-link{:href => "#"} Silabus
                    cargado, pero puedes reemplazarlo.
              .col-md-3
                %label.option.block.option-primary.mt10{:for => "global_notice"}
                  = f.check_box :global_notice, { :class => 'boolean', :id => 'global_notice' }
                  %span.checkbox
                  Noticia Global?
                %label.option.block.option-primary.mt10{:for => "important"}
                  = f.check_box :important, { :class => 'boolean', :id => 'important' }
                  %span.checkbox
                  Importante?

            #divide1.section-divider.mb40.mt20
              %span ¿A quién/quienes va dirigida la noticia?

            #section-divide1.section.row
              .col-md-1
              .col-md-2
                %label.option.block.option-primary.mt10{:for => "teacher"}
                  = check_box 'notice_teacher', '', {id: 'teacher', class: 'boolean'}
                  %span.checkbox
                  Profesor
              .col-md-2
                %label.option.block.option-primary.mt10{:for => "auxiliary"}
                  = check_box 'notice_auxiliary', '', {id: 'auxiliary', class: 'boolean'}
                  %span.checkbox
                  Auxiliar
              .col-md-2
                %label.option.block.option-primary.mt10{:for => "student"}
                  = check_box 'notice_student', '', {id: 'student', class: 'boolean'}
                  %span.checkbox
                  Alumno
              .col-md-3
                .section
                  %label.field
                    %button.btn.btn-primary#put-destinatary{:type => 'button'} Agregar Destinatario

            #body_dest.section.row
              - if @action == 'edit'
                - @notice.notice_details.each do |detail|
                  .col-md-12
                    = hidden_field_tag "notice[notice_details_attributes][" + @reg_n.to_s + "][id]", detail.id
                    = hidden_field_tag "notice[notice_details_attributes][" + @reg_n.to_s + "][notice_id]", @notice.id
                    - if !detail.teacher_id.nil?
                      .col-md-3
                        %label.field.select
                          %select#section{:name => "notice[notice_details_attributes][" + @reg_n.to_s + "][teacher_id]"}
                            %option{:value => ""} Seleccione algún Profesor
                            - Teacher.all.each do |teacher|
                              - if detail.teacher_id == teacher.id
                                %option{:value => "#{teacher.id}", :selected => true}= teacher.first_name.to_s + ' ' + teacher.second_name.to_s + ' ' + teacher.paternal_surname.to_s + ' ' + teacher.maternal_surname.to_s
                              - else
                                %option{:value => "#{teacher.id}"}= teacher.first_name.to_s + ' ' + teacher.second_name.to_s + ' ' + teacher.paternal_surname.to_s + ' ' + teacher.maternal_surname.to_s
                          %i.arrow
                    - if !detail.student_id.nil?
                      .col-md-3
                        %label.field.select
                          %select#section{:name => "notice[notice_details_attributes][" + @reg_n.to_s + "][student_id]"}
                            %option{:value => ""} Seleccione algún Alumno
                            - Student.all.each do |stud|
                              - if detail.student_id == stud.id
                                %option{:value => "#{stud.id}", :selected => true}= stud.first_name.to_s + ' ' + stud.second_name.to_s + ' ' + stud.paternal_surname.to_s + ' ' + stud.maternal_surname.to_s
                              - else
                                %option{:value => "#{stud.id}"}= stud.first_name.to_s + ' ' + stud.second_name.to_s + ' ' + stud.paternal_surname.to_s + ' ' + stud.maternal_surname.to_s
                          %i.arrow
                    - if !detail.auxiliary_id.nil?
                      .col-md-3
                        %label.field.select
                          %select#section{:name => "notice[notice_details_attributes][" + @reg_n.to_s + "][auxiliary_id]"}
                            %option{:value => ""} Seleccione algún Auxiliar
                            - Auxiliary.all.each do |aux|
                              - if detail.auxiliary_id == aux.id
                                %option{:value => "#{aux.id}", :selected => true}= aux.first_name.to_s + ' ' + aux.second_name.to_s + ' ' + aux.paternal_surname.to_s + ' ' + aux.maternal_surname.to_s
                              - else
                                %option{:value => "#{aux.id}"}= aux.first_name.to_s + ' ' + aux.second_name.to_s + ' ' + aux.paternal_surname.to_s + ' ' + aux.maternal_surname.to_s
                          %i.arrow
                  - @reg_n += 1
          .panel-footer.text-right
            %button.button.btn-primary{:type => "submit"} Registrar Noticia
            %button.button{:type => "reset"} Limpiar
          / end .form-footer section
        %a(href="#{notices_path}" class="btn btn-primary" role="button")
          Volver
    / end: .admin-form

:javascript
    
  $(document).ready(function () {

    $('#global_notice').click(function(){
      if($(this).is(":checked")){
        $('#divide1').fadeOut('fast');
        $('#section-divide1').fadeOut('fast');
      } else {
        $('#divide1').fadeIn('fast');
        $('#section-divide1').fadeIn('fast');
      }
    });

    $('#put-destinatary').click(function(){
      teacher_destiny = 0; auxiliary_destiny = 0; student_destiny = 0;

      if( $('#teacher').is(':checked') ){ teacher_destiny = $('#teacher').val(); }
      if( $('#auxiliary').is(':checked') ){ auxiliary_destiny = $('#auxiliary').val(); }
      if( $('#student').is(':checked') ){ student_destiny = $('#student').val(); }
      
      if((teacher_destiny != 0) || (auxiliary_destiny != 0) || (student_destiny != 0)){
        append_url_ajax('#{addRow_notices_path}', 'body_dest', { teacher_selected: teacher_destiny, student_selected: student_destiny, auxiliary_selected: auxiliary_destiny }, 'POST');
      } else {
        new PNotify({
          title: 'Aviso!',
          text: 'Debes especificar a quien va dirigido el aviso.',
          shadow: true,
          opacity: 1,
          addclass: 'stack_top_right',
          type: 'danger',
          width: '300px',
          delay: 2400
        });
      }
    });

    /* @custom validation method (smartCaptcha) 
    ------------------------------------------------------------------ */
        
    $.validator.methods.smartCaptcha = function(value, element, param) {
      return value == param;
    };
            
    $( "#admin-form" ).validate({
    
      /* @validation states + elements 
      ------------------------------------------- */
      
      errorClass: "state-error",
      validClass: "state-success",
      errorElement: "em",
      
      /* @validation rules 
      ------------------------------------------ */
          
      rules: {
        'notice[title]': {
          required: true
        },
        'notice[description]': {
          required: true
        }
      },
      
      /* @validation error messages 
      ---------------------------------------------- */
          
      messages:{
        'notice[title]': {
          required: 'Ingresar Título'
        },
        'notice[description]': {
          required: 'Ingresar Cuerpo de la Noticia.'
        }
      },

      /* @validation highlighting + error placement  
      ---------------------------------------------------- */ 
      
      highlight: function(element, errorClass, validClass) {
              $(element).closest('.field').addClass(errorClass).removeClass(validClass);
      },
      unhighlight: function(element, errorClass, validClass) {
              $(element).closest('.field').removeClass(errorClass).addClass(validClass);
      },
      errorPlacement: function(error, element) {
         if (element.is(":radio") || element.is(":checkbox")) {
                  element.closest('.option-group').after(error);
         } else {
                  error.insertAfter(element.parent());
         }
      }
                    
    });
  });

  function del_bt(dom){
    $(dom).parent().parent().remove();
  }

app/views/notices/_form_row.html.haml
.col-md-12
  - if !@teachers.nil?
    .col-md-4
      %label.field.select
        %select#section{:name => "notice[notice_details_attributes][" + @reg_n.to_s + "][teacher_id]"}
          %option{:value => ""} Seleccione algún Profesor
          - @teachers.each do |teacher|
            %option{:value => "#{teacher.id}"}= teacher.first_name.to_s + ' ' + teacher.second_name.to_s + ' ' + teacher.paternal_surname.to_s + ' ' + teacher.maternal_surname.to_s
        %i.arrow
  - if !@students.nil?
    .col-md-4
      %label.field.select
        %select#section{:name => "notice[notice_details_attributes][" + @reg_n.to_s + "][student_id]"}
          %option{:value => ""} Seleccione algún Alumno
          - @students.each do |stud|
            %option{:value => "#{stud.id}"}= stud.first_name.to_s + ' ' + stud.second_name.to_s + ' ' + stud.paternal_surname.to_s + ' ' + stud.maternal_surname.to_s
        %i.arrow
  - if !@auxiliaries.nil?
    .col-md-3
      %label.field.select
        %select#section{:name => "notice[notice_details_attributes][" + @reg_n.to_s + "][auxiliary_id]"}
          %option{:value => ""} Seleccione algún Auxiliar
          - @auxiliaries.each do |aux|
            %option{:value => "#{aux.id}"}= aux.first_name.to_s + ' ' + aux.second_name.to_s + ' ' + aux.paternal_surname.to_s + ' ' + aux.maternal_surname.to_s
        %i.arrow
  .col-md-1
    %button.btn.btn-danger.btn-sm.deleted-item{:type => 'button', :onclick => 'del_bt(this)'}
      %i.fa.fa-trash-o

app/views/notices/_table.html.haml
.col-md-12
  .panel.panel-visible
    .panel-heading
      .panel-title.hidden-xs
        %span.glyphicon.glyphicon-tasks>
        Lista de Noticias
    .panel-body.pn
      %table.table.table-striped.table-hover{:cellspacing => "0", :width => "100%"}
        %thead
          %tr
            %th #
            %th Título
            %th Acciones
        %tbody
          - @notices.each do |notice|
            %tr
              %td
                = notice.id.to_s
              %td
                = notice.title.to_s
              %td
                %a.btn.btn-success{:href => "#{notice_path(notice.id)}"}
                  Ver Noticia
                %a.btn.btn-warning{:href => "#{edit_notice_path(notice.id)}"}
                  Editar
                %a.btn.btn-danger{:href => "#{notice_path(notice.id)}", "data-method" => 'DELETE'}
                  Eliminar

app/views/notices/edit.html.haml
%h2.lh30.mt15.text-center
  %b.text-primary Editar Noticia

= render :partial => 'form'

app/views/notices/index.html.haml
.bg-light.dark.p30.br-b.br-grey
  %p.lead.mb30
    Lista de Noticias
  - if flash[:notice] !=nil
    %p.lead.mb30
      %b.text-warning
        = flash[:notice]
  - if flash[:error] != nil
    %p.lead.mb30
      %b.text-danger
        = flash[:error]
  .input-group.input-group-merge.input-hero.mb10
    %a.btn.btn-primary.btn-block{:href => "#{new_notice_path}"}
      Registrar Noticia 

.tab-block.p20.mt10
  %section
    = render :partial => 'table'

app/views/notices/new.html.haml
%h2.lh30.mt15.text-center
  %b.text-primary Registrar Noticia

= render :partial => 'form'

app/views/notices/show.html.haml
.row
  .col-sm-3.col-lg-3
  .col-sm-6.col-lg-6
    .panel.panel-info.panel-border.top
      .panel-heading
        %span.panel-title= @notice.title.to_s
      .panel-body
        %p.p2= @notice.description.to_s
        %a.btn.btn-info{:href => "#{notices_path}"}
          %i.fa.fa-reply
          Regresar al Listado de Noticias

app/views/notices/show_all.html.haml
.row
  - @notices_important.each do |notice|
    .col-sm-4.col-lg-4
      .panel.panel-info.panel-border.top
        .panel-heading
          %span.panel-title= notice.title.to_s
        .panel-body
          %p.p2= notice.description.to_s
.row
  - @notices_global.each do |notice|
    .col-sm-4.col-lg-4
      .panel.panel-info.panel-border.top
        .panel-heading
          %span.panel-title= notice.title.to_s
        .panel-body
          %p.p2= notice.description.to_s
- if !@individual_notices.nil?
  .row
    - @individual_notices.each do |notice|
      .col-sm-4.col-lg-4
        .panel.panel-info.panel-border.top
          .panel-heading
            %span.panel-title= notice.title.to_s
          .panel-body
            %p.p2= notice.description.to_s