config/routes.rb
Rails.application.routes.draw do

  get 'global_configurations/putsNotes'
  patch 'global_configurations/update'

  root 'main#index'

  devise_for :users

  resources :courses do
    collection do
      post 'addMoreRows'
    end
  end
  resources :periods do
    member do
      get 'desactivate'
      get 'get_grades'
    end
  end
  resources :homeworks do
    collection do
      post 'complete'
    end
    member do
      get 'desactivate'
      get 'particulary_homework'
    end
  end
  resources :notices do
    collection do
      get 'show_all'
      post 'addRow'
    end
  end
  resources :assists do
    member do
      post 'history'
      get 'particulary_assist'
    end
  end
  resources :teachers
  resources :auxiliaries
  resources :degrees
  resources :timetables do
    collection do
      post 'addMoreRows'
      post 'complete'
    end
  end
  resources :enrolments
  resources :sections_degrees do
    collection do
      post 'addAuxiliaries'
    end
  end
  resources :users, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  resources :grades do
    collection do
      post 'complete'
    end
    member do
      get 'put_grade'
      get 'show_list_students'
      get 'show_grades_student'
      get 'show_report'
      get 'student_grades_pdf'
      post 'student_grades_pdf'
    end
  end

end

app/models/assist.rb
class Assist < ActiveRecord::Base
	has_many :assist_details
	belongs_to :sections_degree
	accepts_nested_attributes_for :assist_details
end

app/models/assist_detail.rb
class AssistDetail < ActiveRecord::Base
	belongs_to :assist
	belongs_to :student
end

app/models/auxiliary.rb
class Auxiliary < User
  has_many :notice_details
  belongs_to :sections_degree_detail
  belongs_to :notice

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_and_belongs_to_many :degrees
	has_many :timetable_details
	has_many :course_details
	has_many :homeworks
	belongs_to :sections_degree

	accepts_nested_attributes_for :course_details, :allow_destroy => true

	has_attached_file :silabus, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	do_not_validate_attachment_file_type :silabus
	#validates_attachment_content_type :silabus, :content_type => /\Aimage\/.*\Z/
end

app/models/course_detail.rb
class CourseDetail < ActiveRecord::Base
  belongs_to :courses
end

app/models/course_grade.rb
class CourseGrade < ActiveRecord::Base
end

app/models/degree.rb
class Degree < ActiveRecord::Base
	has_and_belongs_to_many :courses
	has_many :sections_degrees
end

app/models/grade.rb
class Grade < ActiveRecord::Base
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  belongs_to :courses
  has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
end

app/models/notice.rb
class Notice < ActiveRecord::Base
	has_many :notice_details
	has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
	
	accepts_nested_attributes_for :notice_details, :allow_destroy => true
end

app/models/notice_detail.rb
class NoticeDetail < ActiveRecord::Base
	belongs_to :notice
	belongs_to :teachers
	belongs_to :auxiliaries
	belongs_to :students
end

app/models/period.rb
class Period < ActiveRecord::Base
end

app/models/rating.rb
class Rating < ActiveRecord::Base
end

app/models/student.rb
class Student < User
  has_many :student_details
  has_many :assist_details
  has_many :notice_details
  belongs_to :sections_degree
  belongs_to :notice

  accepts_nested_attributes_for :student_details
end

app/models/student_place.rb
class StudentPlace < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < User
  has_many :timetable_details
  has_many :notice_details
  belongs_to :notice

end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
	has_many :timetable_details
	belongs_to :sections_degree

	accepts_nested_attributes_for :timetable_details, :allow_destroy => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  include RoleModel
  roles :director, :administrator, :assistant, :student, :teacher

end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @periods = Period.all
  end

  def new
    @period = Period.new
    if Period.last.nil?
      @lastperiod = ''
    else
      @lastperiod = Period.last.end_date
    end
  end

  def create
    period = Period.new(params_period)
    period.status = 1
    period.grade_flag = 1
    period.save
    redirect_to :action => :index
  end

  def edit
    @period = Period.find(params[:id])
  end

  def update
    period = Period.find(params[:id]).update_attributes(params_period)
    redirect_to :action => :index
  end

  def destroy
    period = Period.destroy(params[:id])
    redirect_to :action => :index
  end

  def get_grades
    period = Period.find(params[:id])
    timetables = Timetable.all
    timetables.each do |tt|
      numberplaces = 1
      course_array = Array.new
      tt.timetable_details.each do |ttd|
        course_array << ttd.course_id
      end
      students = User.where("type LIKE 'Student' AND sections_degree_id = ?", tt.sections_degree_id)
      students.each do |st|
        course_array.each do |co|
          course = Course.find(co)
          course_detail_array = Array.new
          course.course_details.each do |cod|
            course_detail_array << cod.id
            cdg = CourseDetailGrade.new
            cdg.date_of_issue = Time.now.to_date
            cdg.course_id = co
            cdg.course_detail_id = cod.id
            cdg.student_id = st.id
            cdg.period_id = period.id
            period_grade = Grade.where("student_id = ? AND course_detail_id = ? AND date_of_issue BETWEEN ? AND ?", st.id, cod.id, period.start_date, period.end_date).average(:grade)
            if period_grade != nil
              cdg.grade = period_grade.round(2)
            else
              cdg.grade = 0
            end
            cdg.save
          end
          cgrade = CourseGrade.new
          cgrade.date_of_issue = Time.now.to_date
          cgrade.course_id = co
          cgrade.student_id = st.id
          cperiod_grade = CourseDetailGrade.where("student_id = ? AND course_id = ? AND date_of_issue BETWEEN ? AND ?", st.id, co, period.start_date, period.end_date).average(:grade)
          if cperiod_grade != nil
            cgrade.grade = cperiod_grade.round(2)
          else
            cgrade.grade = 0
          end
          cgrade.period_id = period.id
          cgrade.save
        end
        places = StudentPlace.new
        places.user_id = st.id
        places.sections_degree_id = tt.sections_degree_id
        places.gradeaverage = (CourseGrade.where("student_id = ? AND period_id = ?", st.id, period.id).average(:grade)).to_f
        places.period_id = period.id
        places.save
      end
      orderedplaces = ActiveRecord::Base.connection.execute("
        SELECT id 
        FROM student_places 
        WHERE sections_degree_id = '"+tt.sections_degree_id.to_s+"'
        ORDER BY gradeaverage DESC
      ")
      orderedplaces.each do |op|
        orderpla = StudentPlace.find(op[0])
        orderpla.place = numberplaces
        orderpla.save
        numberplaces = numberplaces + 1
      end
    end
    period.grade_flag = 0
    period.save
    redirect_to :action => :index
  end

  def desactivate
    period = Period.find(params[:id])
    period.status = 0
    period.save
    redirect_to :action => :index
  end

  private
  def params_period
    params.require(:period).permit(
      :name,
      :start_date,
      :end_date
    )
  end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/periods/_form.html.haml
.row
  .col-md-9.center-block
    / Form Wizard
    .admin-form.theme-primary
      .panel
        = simple_form_for(@period, html: {id: 'admin-form', autocomplete: 'off' }) do |f|
          .panel-body
            .section.row
              .col-md-4
                %label.field.prepend-icon{:for => "name"}
                  = f.input :name, placeholder: "Nombre", input_html: { id: 'name', class: 'gui-input' }, label: false, :wrapper => false
                  %label.field-icon{:for => "name"}
                    %i.fa.fa-user
              .col-md-4
                %label.field.prepend-icon{:for => "start_date"}
                  = f.input :start_date, as: :string, placeholder: "Fecha de Inicio", input_html: { id: 'start-date', class: 'gui-input', :type => "date" }, label: false, :wrapper => false
                  %label.field-icon{:for => "start_date"}
                    %i.fa.fa-user
              .col-md-4
                %label.field.prepend-icon{:for => "end_date"}
                  = f.input :end_date, as: :string, placeholder: "Fecha de Fin", input_html: { id: 'end-date', class: 'gui-input', :type => "date" }, label: false, :wrapper => false
                  %label.field-icon{:for => "end_date"}
                    %i.fa.fa-user
          .panel-footer.text-right
            %button.button.btn-primary{:type => "submit"} Registrar Periodo
            %button.button{:type => "reset"} Limpiar
          / end .form-footer section
        %a(href="#{periods_path}" class="btn btn-primary" role="button")
          Volver
    / end: .admin-form
#modal-text.popup-basic.p25.mfp-with-anim.mfp-hide
  %h2.lh30.mt15.text-center
    %b.text-primary Cargando
  %p.text-center Espere un momento Porfavor

:javascript
  $(document).ready(function () {
    /* @custom validation method (smartCaptcha) 
    ------------------------------------------------------------------ */
        
    $.validator.methods.smartCaptcha = function(value, element, param) {
      return value == param;
    };

    $( "#admin-form" ).validate({
    
      /* @validation states + elements 
      ------------------------------------------- */
      
      errorClass: "state-error",
      validClass: "state-success",
      errorElement: "em",
      
      /* @validation rules 
      ------------------------------------------ */
          
      rules: {
        'period[name]': {
          required: true
        }
      },
      
      /* @validation error messages 
      ---------------------------------------------- */
          
      messages:{
        'period[name]': {
          required: 'Ingresar Nombre'
        }
      },

      /* @validation highlighting + error placement  
      ---------------------------------------------------- */ 
      
      highlight: function(element, errorClass, validClass) {
              $(element).closest('.field').addClass(errorClass).removeClass(validClass);
      },
      unhighlight: function(element, errorClass, validClass) {
              $(element).closest('.field').removeClass(errorClass).addClass(validClass);
      },
      errorPlacement: function(error, element) {
         if (element.is(":radio") || element.is(":checkbox")) {
                  element.closest('.option-group').after(error);
         } else {
                  error.insertAfter(element.parent());
         }
      }                    
    });

            
  });

  function submit_validate(form){
    $(form['selector']).ajaxForm({
      beforeSubmit: function() {
        $( "#admin-form" ).validate({
    
          /* @validation states + elements 
          ------------------------------------------- */
          
          errorClass: "state-error",
          validClass: "state-success",
          errorElement: "em",
          
          /* @validation rules 
          ------------------------------------------ */
              
          rules: {
            'period[name]': {
              required: true
            }
          },
          
          /* @validation error messages 
          ---------------------------------------------- */
              
          messages:{
            'period[name]': {
              required: 'Ingresar Nombre'
            }
          },

          /* @validation highlighting + error placement  
          ---------------------------------------------------- */ 
          
          highlight: function(element, errorClass, validClass) {
                  $(element).closest('.field').addClass(errorClass).removeClass(validClass);
          },
          unhighlight: function(element, errorClass, validClass) {
                  $(element).closest('.field').removeClass(errorClass).addClass(validClass);
          },
          errorPlacement: function(error, element) {
             if (element.is(":radio") || element.is(":checkbox")) {
                      element.closest('.option-group').after(error);
             } else {
                      error.insertAfter(element.parent());
             }
          }                    
        });
        if( $(form['selector']).valid() ){
          $('#modal-text').modal();
        }
        
        return $(form['selector']).valid();
      },
      target: '#content',
      success: function (data){
        $('#modal-text').modal('hide');
      },
      error: function(xhr, status, error) {
        $('#modal-text').modal('hide');
      }
    });
  }

  $('#start-date').change(function(){
    var start_date = $('#start-date').val();
    var end_date = '#{@lastperiod}';
    console.log(start_date);
    console.log(end_date);

    if(end_date>start_date) {
      document.getElementById("start-date").value = '';
      new PNotify({
        title: 'Problema con las fechas.',
        text: 'La fecha del nuevo periodo no puede estar dentro del anterior.',
        shadow: true,
        opacity: 1,
        addclass: 'stack_top_right',
        type: 'danger',
        width: '300px',
        delay: 2400
      });
    }
  });

app/views/periods/_table.html.haml
.col-md-12
  .panel.panel-visible
    .panel-heading
      .panel-title.hidden-xs
        %span.glyphicon.glyphicon-tasks>
        Lista de Periodos
    .panel-body.pn
      %table.table.table-striped.table-hover{:cellspacing => "0", :width => "100%"}
        %thead
          %tr
            %th Nombre
            %th Fecha de Inicio
            %th Fecha de Fin
            %th Acciones
        %tbody
          - @periods.each do |period|
            %tr
              %td
                = period.name.to_s
              %td
                = period.start_date
              %td
                = period.end_date
              %td
                -if period.status == 1
                  %a.btn.btn-danger{:href => "#{desactivate_period_path(period.id)}"}
                    Desactivar
                -if period.grade_flag == 1
                  %a.btn.btn-success{:href => "#{get_grades_period_path(period.id)}"}
                    Obtener Notas
                %a.btn.btn-warning{:href => "#{edit_period_path(period.id)}"}
                  Editar
                %a.btn.btn-danger{:href => "#{period_path(period.id)}", 'data-method' => 'DELETE'}
                  Eliminar

app/views/periods/edit.html.haml
%h2.lh30.mt15.text-center
  %b.text-primary Editar Periodo

= render :partial => 'form'

app/views/periods/index.html.haml
.bg-light.dark.p30.br-b.br-grey
  %p.lead.mb30
    Lista de Periodos
  - if flash[:notice] !=nil
    %p.lead.mb30
      %b.text-warning
        = flash[:notice]
  - if flash[:error] != nil
    %p.lead.mb30
      %b.text-danger
        = flash[:error]
  .input-group.input-group-merge.input-hero.mb10
    %a.btn.btn-primary.btn-block{:href => "#{new_period_path}"}
      Registrar Periodo 

.tab-block.p20.mt10
  %section
    = render :partial => 'table'

app/views/periods/new.html.haml
%h2.lh30.mt15.text-center
  %b.text-primary Registrar Periodo

= render :partial => 'form'