config/routes.rb
Rails.application.routes.draw do

  get 'global_configurations/putsNotes'
  patch 'global_configurations/update'

  root 'main#index'

  devise_for :users

  resources :courses do
    collection do
      post 'addMoreRows'
    end
  end
  resources :periods do
    member do
      get 'desactivate'
      get 'get_grades'
    end
  end
  resources :homeworks do
    collection do
      post 'complete'
    end
    member do
      get 'desactivate'
      get 'particulary_homework'
    end
  end
  resources :notices do
    collection do
      get 'show_all'
      post 'addRow'
    end
  end
  resources :assists do
    member do
      post 'history'
      get 'particulary_assist'
    end
  end
  resources :teachers
  resources :auxiliaries
  resources :degrees
  resources :timetables do
    collection do
      post 'addMoreRows'
      post 'complete'
    end
  end
  resources :enrolments
  resources :sections_degrees do
    collection do
      post 'addAuxiliaries'
    end
  end
  resources :users, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  resources :grades do
    collection do
      post 'complete'
    end
    member do
      get 'put_grade'
      get 'show_list_students'
      get 'show_grades_student'
      get 'show_report'
      get 'student_grades_pdf'
      post 'student_grades_pdf'
    end
  end

end

app/models/assist.rb
class Assist < ActiveRecord::Base
	has_many :assist_details
	belongs_to :sections_degree
	accepts_nested_attributes_for :assist_details
end

app/models/assist_detail.rb
class AssistDetail < ActiveRecord::Base
	belongs_to :assist
	belongs_to :student
end

app/models/auxiliary.rb
class Auxiliary < User
  has_many :notice_details
  belongs_to :sections_degree_detail
  belongs_to :notice

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_and_belongs_to_many :degrees
	has_many :timetable_details
	has_many :course_details
	has_many :homeworks
	belongs_to :sections_degree

	accepts_nested_attributes_for :course_details, :allow_destroy => true

	has_attached_file :silabus, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	do_not_validate_attachment_file_type :silabus
	#validates_attachment_content_type :silabus, :content_type => /\Aimage\/.*\Z/
end

app/models/course_detail.rb
class CourseDetail < ActiveRecord::Base
  belongs_to :courses
end

app/models/course_grade.rb
class CourseGrade < ActiveRecord::Base
end

app/models/degree.rb
class Degree < ActiveRecord::Base
	has_and_belongs_to_many :courses
	has_many :sections_degrees
end

app/models/grade.rb
class Grade < ActiveRecord::Base
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  belongs_to :courses
  has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
end

app/models/notice.rb
class Notice < ActiveRecord::Base
	has_many :notice_details
	has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
	
	accepts_nested_attributes_for :notice_details, :allow_destroy => true
end

app/models/notice_detail.rb
class NoticeDetail < ActiveRecord::Base
	belongs_to :notice
	belongs_to :teachers
	belongs_to :auxiliaries
	belongs_to :students
end

app/models/period.rb
class Period < ActiveRecord::Base
end

app/models/rating.rb
class Rating < ActiveRecord::Base
end

app/models/student.rb
class Student < User
  has_many :student_details
  has_many :assist_details
  has_many :notice_details
  belongs_to :sections_degree
  belongs_to :notice

  accepts_nested_attributes_for :student_details
end

app/models/student_place.rb
class StudentPlace < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < User
  has_many :timetable_details
  has_many :notice_details
  belongs_to :notice

end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
	has_many :timetable_details
	belongs_to :sections_degree

	accepts_nested_attributes_for :timetable_details, :allow_destroy => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  include RoleModel
  roles :director, :administrator, :assistant, :student, :teacher

end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  before_filter :authenticate_user!
  def index
    @degrees = Degree.order('name ASC')
  end

  def new
    @degree = Degree.new
  end

  def create
    degree = Degree.new(params_degree)
    degree.save
    redirect_to :action => :index
  end

  def edit
    @degree = Degree.find(params[:id])
  end

  def update
    degree = Degree.find(params[:id]).update_attributes(params_degree)
    redirect_to :action => :index
  end

  def destroy
    degree = Degree.destroy(params[:id])
    redirect_to :action => :index
  end

  private
  def params_degree
    params.require(:degree).permit(
      :name
    )
  end
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/degrees/_form.html.haml
.row
  .col-md-9.center-block
    / Form Wizard
    .admin-form.theme-primary
      .panel
        = simple_form_for(@degree, html: {id: 'admin-form', autocomplete: 'off' }) do |f|
          .panel-body
            .section.row
              .col-md-4
                %label.field.prepend-icon{:for => "name"}
                  = f.input :name, placeholder: "Nombre", input_html: { id: 'name', class: 'gui-input' }, label: false, :wrapper => false
                  %label.field-icon{:for => "name"}
                    %i.fa.fa-user
          .panel-footer.text-right
            %button.button.btn-primary{:type => "submit"} Registrar Curso
            %button.button{:type => "reset"} Limpiar
          / end .form-footer section
        %a(href="#{degrees_path}" class="btn btn-primary" role="button")
          Volver
    / end: .admin-form

:javascript
  $(document).ready(function () {
    /* @custom validation method (smartCaptcha) 
    ------------------------------------------------------------------ */
        
    $.validator.methods.smartCaptcha = function(value, element, param) {
      return value == param;
    };
            
    $( "#admin-form" ).validate({
    
      /* @validation states + elements 
      ------------------------------------------- */
      
      errorClass: "state-error",
      validClass: "state-success",
      errorElement: "em",
      
      /* @validation rules 
      ------------------------------------------ */
          
      rules: {
        'degree[name]': {
          required: true
        }
      },
      
      /* @validation error messages 
      ---------------------------------------------- */
          
      messages:{
        'degree[name]': {
          required: 'Ingresar Nombre'
        }
      },

      /* @validation highlighting + error placement  
      ---------------------------------------------------- */ 
      
      highlight: function(element, errorClass, validClass) {
              $(element).closest('.field').addClass(errorClass).removeClass(validClass);
      },
      unhighlight: function(element, errorClass, validClass) {
              $(element).closest('.field').removeClass(errorClass).addClass(validClass);
      },
      errorPlacement: function(error, element) {
         if (element.is(":radio") || element.is(":checkbox")) {
                  element.closest('.option-group').after(error);
         } else {
                  error.insertAfter(element.parent());
         }
      }
                    
    });
  });

app/views/degrees/_table.html.haml
.col-md-12
  .panel.panel-visible
    .panel-heading
      .panel-title.hidden-xs
        %span.glyphicon.glyphicon-tasks>
        Lista de Grados
    .panel-body.pn
      %table.table.table-striped.table-hover{:cellspacing => "0", :width => "100%"}
        %thead
          %tr
            %th Nombre
            %th Acciones
        %tbody
          - @degrees.each do |degree|
            %tr
              %td
                = degree.name.to_s
              %td
                %a.btn.btn-warning{:href => "#{edit_degree_path(degree.id)}"}
                  Editar
                %a.btn.btn-danger{:href => "#{degree_path(degree.id)}", 'data-method' => 'DELETE'}
                  Eliminar

app/views/degrees/edit.html.haml
%h2.lh30.mt15.text-center
  %b.text-primary Editar Grado

= render :partial => 'form'

app/views/degrees/index.html.haml
.bg-light.dark.p30.br-b.br-grey
  %p.lead.mb30
    Lista de Grados
  - if flash[:notice] !=nil
    %p.lead.mb30
      %b.text-warning
        = flash[:notice]
  - if flash[:error] != nil
    %p.lead.mb30
      %b.text-danger
        = flash[:error]
  .input-group.input-group-merge.input-hero.mb10
    %a.btn.btn-primary.btn-block{:href => "#{new_degree_path}"}
      Registrar Grado 

.tab-block.p20.mt10
  %section
    = render :partial => 'table'

app/views/degrees/new.html.haml
%h2.lh30.mt15.text-center
  %b.text-primary Registrar Grado

= render :partial => 'form'