config/routes.rb
Rails.application.routes.draw do

  get 'global_configurations/putsNotes'
  patch 'global_configurations/update'

  root 'main#index'

  devise_for :users

  resources :courses do
    collection do
      post 'addMoreRows'
    end
  end
  resources :periods do
    member do
      get 'desactivate'
      get 'get_grades'
    end
  end
  resources :homeworks do
    collection do
      post 'complete'
    end
    member do
      get 'desactivate'
      get 'particulary_homework'
    end
  end
  resources :notices do
    collection do
      get 'show_all'
      post 'addRow'
    end
  end
  resources :assists do
    member do
      post 'history'
      get 'particulary_assist'
    end
  end
  resources :teachers
  resources :auxiliaries
  resources :degrees
  resources :timetables do
    collection do
      post 'addMoreRows'
      post 'complete'
    end
  end
  resources :enrolments
  resources :sections_degrees do
    collection do
      post 'addAuxiliaries'
    end
  end
  resources :users, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  resources :grades do
    collection do
      post 'complete'
    end
    member do
      get 'put_grade'
      get 'show_list_students'
      get 'show_grades_student'
      get 'show_report'
      get 'student_grades_pdf'
      post 'student_grades_pdf'
    end
  end

end

app/models/assist.rb
class Assist < ActiveRecord::Base
	has_many :assist_details
	belongs_to :sections_degree
	accepts_nested_attributes_for :assist_details
end

app/models/assist_detail.rb
class AssistDetail < ActiveRecord::Base
	belongs_to :assist
	belongs_to :student
end

app/models/auxiliary.rb
class Auxiliary < User
  has_many :notice_details
  belongs_to :sections_degree_detail
  belongs_to :notice

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_and_belongs_to_many :degrees
	has_many :timetable_details
	has_many :course_details
	has_many :homeworks
	belongs_to :sections_degree

	accepts_nested_attributes_for :course_details, :allow_destroy => true

	has_attached_file :silabus, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	do_not_validate_attachment_file_type :silabus
	#validates_attachment_content_type :silabus, :content_type => /\Aimage\/.*\Z/
end

app/models/course_detail.rb
class CourseDetail < ActiveRecord::Base
  belongs_to :courses
end

app/models/course_grade.rb
class CourseGrade < ActiveRecord::Base
end

app/models/degree.rb
class Degree < ActiveRecord::Base
	has_and_belongs_to_many :courses
	has_many :sections_degrees
end

app/models/grade.rb
class Grade < ActiveRecord::Base
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  belongs_to :courses
  has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
end

app/models/notice.rb
class Notice < ActiveRecord::Base
	has_many :notice_details
	has_attached_file :attachment, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
	
	accepts_nested_attributes_for :notice_details, :allow_destroy => true
end

app/models/notice_detail.rb
class NoticeDetail < ActiveRecord::Base
	belongs_to :notice
	belongs_to :teachers
	belongs_to :auxiliaries
	belongs_to :students
end

app/models/period.rb
class Period < ActiveRecord::Base
end

app/models/rating.rb
class Rating < ActiveRecord::Base
end

app/models/student.rb
class Student < User
  has_many :student_details
  has_many :assist_details
  has_many :notice_details
  belongs_to :sections_degree
  belongs_to :notice

  accepts_nested_attributes_for :student_details
end

app/models/student_place.rb
class StudentPlace < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < User
  has_many :timetable_details
  has_many :notice_details
  belongs_to :notice

end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
	has_many :timetable_details
	belongs_to :sections_degree

	accepts_nested_attributes_for :timetable_details, :allow_destroy => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  include RoleModel
  roles :director, :administrator, :assistant, :student, :teacher

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :authenticate_user!
  def index
    @teachers = Teacher.all.order(:first_name)
  end

  def new
    @teacher = Teacher.new
    @time = Time.now.to_date
  end

  def create
    teacher = Teacher.new(params_teacher)
    generated_passw = Devise.friendly_token.first(8)
    teacher.email = teacher.first_name.to_s.downcase[0] + '.' + teacher.paternal_surname.to_s + '@loremipsum.com'
    teacher.password = generated_passw
    teacher.password_confirmation = generated_passw
    teacher.roles = [:teacher]
    if teacher.save
      UserMailer.send_new_user_message(teacher,generated_passw).deliver_now
      flash[:notice] = "Profesor #{teacher.first_name.to_s + ' ' + teacher.second_name.to_s + ' ' + teacher.paternal_surname.to_s + ' ' + teacher.maternal_surname.to_s} registrado."
    else
      if teacher.errors.added?(:email, :taken)
        teacher.email = teacher.first_name.to_s.downcase[0] + teacher.second_name.to_s.downcase[0] + '.' + teacher.paternal_surname.to_s + '@loremipsum.com'
        if teacher.save
          UserMailer.send_new_user_message(teacher,generated_passw).deliver_now
          flash[:notice] = "Alumno #{teacher.first_name.to_s + ' ' + teacher.second_name.to_s + ' ' + teacher.paternal_surname.to_s + ' ' + teacher.maternal_surname.to_s} Matriculado."
        else
          flash[:notice] = "Este Profesor tiene los mismos nombres y primer apellido iguales a otro ya registrado. ¿Está seguro del registro?."
        end
      end
    end
    redirect_to :action => :index
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    teacher = Teacher.find(params[:id]).update_attributes(params_teacher)
    redirect_to :action => :index
  end

  def destroy
    @teacher = Teacher.destroy(params[:id])
    redirect_to :action => :index
  end

  private
  def params_teacher
    params.require(:teacher).permit(
      :first_name, 
      :second_name, 
      :paternal_surname, 
      :maternal_surname, 
      :date_of_birth, 
      :owner_email,
      :dni, 
      :phone, 
      :address
    )
  end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/teachers/_form.html.haml
.row
  .col-md-9.center-block
    / Form Wizard
    .admin-form.theme-primary
      .panel
        = simple_form_for(@teacher, html: {id: 'admin-form', autocomplete: 'off' }) do |f|
          .panel-body
            .section.row
              .col-md-4
                %label.field.prepend-icon{:for => "first_name"}
                  = f.input :first_name, placeholder: "Primer Nombre", input_html: { id: 'first_name', class: 'gui-input' }, label: false, :wrapper => false
                  %label.field-icon{:for => "first_name"}
                    %i.fa.fa-user
              .col-md-4
                %label.field.prepend-icon{:for => "second_name"}
                  = f.input :second_name, placeholder: "Segundo Nombre", input_html: { id: 'second_name', class: 'gui-input' }, label: false, :wrapper => false
                  %label.field-icon{:for => "second_name"}
                    %i.fa.fa-user
              .col-md-4
                %label.field.prepend-icon{:for => "paternal_surname"}
                  = f.input :paternal_surname, placeholder: "Apellido Paterno", input_html: { id: 'paternal_surname', class: 'gui-input' }, label: false, :wrapper => false
                  %label.field-icon{:for => "paternal_surname"}
                    %i.fa.fa-user
            .section.row
              .col-md-4
                %label.field.prepend-icon{:for => "maternal_surname"}
                  = f.input :maternal_surname, placeholder: "Apellido Materno", input_html: { id: 'maternal_surname', class: 'gui-input' }, label: false, :wrapper => false
                  %label.field-icon{:for => "maternal_surname"}
                    %i.fa.fa-user
              .col-md-4
                %label.field.prepend-icon{:for => "date_of_birth"}
                  = f.input :date_of_birth, as: :string, placeholder: "Fecha de Nacimiento", input_html: { id: 'date-of-birth', class: 'gui-input', :type => "date" }, label: false, :wrapper => false
                  %label.field-icon{:for => "date_of_birth"}
                    %i.fa.fa-user
              .col-md-4
                %label.field.prepend-icon{:for => "dni"}
                  = f.input :dni, placeholder: "DNI / C. de Extranjería", input_html: { id: 'dni', class: 'gui-input' }, label: false, :wrapper => false
                  %label.field-icon{:for => "dni"}
                    %i.fa.fa-user
            .section.row
              .col-md-4
                %label.field.prepend-icon{:for => "phone"}
                  = f.input :phone, placeholder: "Telefono", input_html: { id: 'phone', class: 'gui-input' }, label: false, :wrapper => false
                  %label.field-icon{:for => "phone"}
                    %i.fa.fa-user
              .col-md-4
                %label.field.prepend-icon{:for => "owner_email"}
                  = f.input :owner_email, placeholder: "Email Personal", input_html: { id: 'owner_email', class: 'gui-input' }, label: false, :wrapper => false, :type => 'email'
                  %label.field-icon{:for => "owner_email"}
                    %i.fa.fa-user
              .col-md-4
                %label.field.prepend-icon{:for => "address"}
                  = f.input :address, placeholder: "Direccion", input_html: { id: 'address', class: 'gui-textarea' }, label: false, :wrapper => false
                  %label.field-icon{:for => "address"}
                    %i.fa.fa-comments

          .panel-footer.text-right
            %button.button.btn-primary{:type => "submit", :onclick => "block();"} Registrar Profesor
            %button.button{:type => "reset"} Limpiar
          / end .form-footer section
        %a(href="#{teachers_path}" class="btn btn-primary" role="button")
          Volver
    / end: .admin-form

:javascript
  $(document).ready(function () {
    /* @custom validation method (smartCaptcha) 
    ------------------------------------------------------------------ */
        
    $.validator.methods.smartCaptcha = function(value, element, param) {
      return value == param;
    };
            
    $( "#admin-form" ).validate({
    
      /* @validation states + elements 
      ------------------------------------------- */
      
      errorClass: "state-error",
      validClass: "state-success",
      errorElement: "em",
      
      /* @validation rules 
      ------------------------------------------ */
          
      rules: {
        'teacher[first_name]': {
          required: true
        },
        'teacher[paternal_surname]': {
          required: true
        },
        'teacher[maternal_surname]': {
          required: true
        },
        'teacher[date_of_birth]': {
          required: true,
          max: "#{@time}"
        },
        'teacher[owner_email]': {
          required: true,
          email: true
        },
        'teacher[dni]': {
          required: true,
          minlength : 8,
          maxlength : 11
        },
        'teacher[phone]': {
          required: true,
          minlength : 7,
          maxlength : 9
        },
        'teacher[address]': {
          required: true
        }
      },
      
      /* @validation error messages 
      ---------------------------------------------- */
          
      messages:{
        'teacher[first_name]': {
          required: 'Ingresa Primer Nombre'
        },
        'teacher[paternal_surname]': {
          required: 'Ingresa Primer Apellido'
        },
        'teacher[maternal_surname]': {
          required: 'Ingresa Segundo Apellido'
        },
        'teacher[date_of_birth]': {
          required: 'Ingresa Fecha de Nacimiento',
          max: 'El valor no puede ser mayor a la fecha actual.'
        },
        'teacher[owner_email]': {
          required: 'Ingese un email',
          email: 'Ingrese un email válido.'
        },
        'teacher[dni]': {
          required: 'Ingresa DNI / C. Extranjería',
          maxlength: 'Debe ser 8 o 11 digitos',
          minlength: 'Debe ser 8 o 11 dígitos'
        },
        'teacher[phone]': {
          required: 'Ingresa Teléfono',
          maxlength: 'Debe ser 7 o 9 digitos',
          minlength: 'Debe ser 7 o 9 dígitos'
        },
        'teacher[address]': {
          required: 'Ingresa Dirección'
        }
      },

      /* @validation highlighting + error placement  
      ---------------------------------------------------- */ 
      
      highlight: function(element, errorClass, validClass) {
              $(element).closest('.field').addClass(errorClass).removeClass(validClass);
      },
      unhighlight: function(element, errorClass, validClass) {
              $(element).closest('.field').removeClass(errorClass).addClass(validClass);
      },
      errorPlacement: function(error, element) {
         if (element.is(":radio") || element.is(":checkbox")) {
                  element.closest('.option-group').after(error);
         } else {
                  error.insertAfter(element.parent());
         }
      }
                    
    });

    $('#date-of-birth').keypress(function(e){
      e.preventDefault();
    });
  });

  function block(){
    $.magnificPopup.open({
      removalDelay: 500,
      items: {
        src: '#modal-text-loading'
      },
      // overflowY: 'hidden', // 
      callbacks: {
        beforeOpen: function(e) {
          this.st.mainClass = 'mfp-zoomOut';
        }
      },
      midClick: true
    });
  }

app/views/teachers/_table.html.haml
.col-md-12
  .panel.panel-visible
    .panel-heading
      .panel-title.hidden-xs
        %span.glyphicon.glyphicon-tasks>
        Lista de Profesores
    .panel-body.pn
      %table.table.table-striped.table-hover{:cellspacing => "0", :width => "100%"}
        %thead
          %tr
            %th Nombre
            %th DNI
            %th Teléfono
            %th Acciones
        %tbody
          - @teachers.each do |teacher|
            %tr
              %td
                = teacher.first_name.to_s + ' ' + teacher.second_name.to_s + ' ' + teacher.paternal_surname.to_s + ' ' + teacher.maternal_surname.to_s
              %td
                = teacher.dni.to_s
              %td
                = teacher.phone.to_s
              %td
                %a.btn.btn-warning{:href => "#{edit_teacher_path(teacher.id)}"}
                  Editar
                %a.btn.btn-danger{:href => "#{teacher_path(teacher.id)}", 'data-method' => 'DELETE'}
                  Eliminar

app/views/teachers/edit.html.haml
%h2.lh30.mt15.text-center
  %b.text-primary Editar Profesor

= render :partial => 'form'

app/views/teachers/index.html.haml
.bg-light.dark.p30.br-b.br-grey
  %p.lead.mb30
    Lista de Profesores
  - if flash[:notice] !=nil
    %p.lead.mb30
      %b.text-warning
        = flash[:notice]
  - if flash[:error] != nil
    %p.lead.mb30
      %b.text-danger
        = flash[:error]
  .input-group.input-group-merge.input-hero.mb10
    %a.btn.btn-primary.btn-block{:href => "#{new_teacher_path}"}
      Registrar Profesor 

.tab-block.p20.mt10
  %section
    = render :partial => 'table'

app/views/teachers/new.html.haml
%h2.lh30.mt15.text-center
  %b.text-primary Registrar Profesor

= render :partial => 'form'